### ISSUE TITLE
cant fetch token

### ISSUE THREAD

**Issue by der-lu** [shuichiro-makigaki/mendeley_cli#10]
unfortunately i alway get the following output

Traceback (most recent call last):
  File "/home/derlu/.local/bin/mendeley", line 5, in <module>
    from mendeley_cli import cmd
  File "/home/derlu/.local/lib/python3.10/site-packages/mendeley_cli/__init__.py", line 12, in <module>
    from yandeley import Mendeley, MendeleyAuthorizationCodeAuthenticator
  File "/home/derlu/.local/lib/python3.10/site-packages/yandeley/__init__.py", line 7, in <module>
    from yandeley.auth import MendeleyClientCredentialsAuthenticator, \
  File "/home/derlu/.local/lib/python3.10/site-packages/yandeley/auth.py", line 4, in <module>
    from requests.auth import HTTPBasicAuth
  File "/home/derlu/.local/lib/python3.10/site-packages/requests/__init__.py", line 58, in <module>
    from . import utils
  File "/home/derlu/.local/lib/python3.10/site-packages/requests/utils.py", line 26, in <module>
    from .compat import parse_http_list as _parse_list_header
  File "/home/derlu/.local/lib/python3.10/site-packages/requests/compat.py", line 7, in <module>
    from .packages import chardet
  File "/home/derlu/.local/lib/python3.10/site-packages/requests/packages/__init__.py", line 3, in <module>
    from . import urllib3
  File "/home/derlu/.local/lib/python3.10/site-packages/requests/packages/urllib3/__init__.py", line 10, in <module>
    from .connectionpool import (
  File "/home/derlu/.local/lib/python3.10/site-packages/requests/packages/urllib3/connectionpool.py", line 38, in <module>
    from .response import HTTPResponse
  File "/home/derlu/.local/lib/python3.10/site-packages/requests/packages/urllib3/response.py", line 5, in <module>
    from ._collections import HTTPHeaderDict
  File "/home/derlu/.local/lib/python3.10/site-packages/requests/packages/urllib3/_collections.py", line 1, in <module>
    from collections import Mapping, MutableMapping
ImportError: cannot import name 'Mapping' from 'collections' (/usr/lib/python3.10/collections/__init__.py)

what am i doing wrong?

**Comment by shuichiro-makigaki** [comment]
I have reproduced this problem here as well.
I found that the current mendeley_cli does not support Python 3.10.
Please use Python 3.9 instead; that is a workaround.

I filed this issue at #11.

**Comment by der-lu** [comment]
Thank you very much
